var speak = [
    '&byeText',
    '&1layerAnnounce',
    '&pause',
    '&hiText',
    '&byeLayer',
    'Soobin\'s phone rings.',
    '&soobin',
    '&soobinName',
    '"Hello?"',
    '&soobinBye',
    '&taehyun',
    '&taehyunName',
    '"We have a task for you in the office. Come in NOW!!!!!!!!!!!!!!"',
    '&taehyunBye',
    '&soobin',
    '&soobinName',
    '"Okay okay okay!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"',
    '&nameBye',
    '&bgOffice',
    'Soobin arrives at the office.',
    '&taehyun',
    '&taehyunName',
    '"Soobin. we have a BIG TASK FOR YOU!!!!"',
    '"You must deliver a file that an offshore client has requested."',
    '&taehyunNameAlt',
    '"Also my alternate name is HTTP."',
    '"It stands for Hyun Tae Tae Pop."',
    '&soobinName',
    '"Oh... okay!"',
    '"I will do my SOOBIN best!"',
    '&nameBye',
    '&soobinBye',
    '&taehyunBye',
    '&bgComputer',
    'Soobin looks at his computer in disarray.',
    'How in the world does he respond to a GET request for a file?',
    '&soobinName',
    '&soobin',
    '"Oh golly gee... this makes no sense! I hate my stupid job!"',
    '"No... I can\'t give up! I have to keep trying!"',
    '&soobinBye',
    '&byeText',
    '&nameBye',
    '&computerScreen',
    '&pause',
    '&soobin',
    '&soobinName',
    '&hiText',
    '"What\'s this...? GET /give2beomgyu.txt HTTP/1.0?"',
    '"Where have I heard those last three letters on the give2beomgyu file?"',
    '"Oh well. I know just what to do! I have to go deliver this file!"',
    '&computerScreenBye',
    '&soobinBye',
    '&byeText',
    '&nameBye',
    '&filing',
    '&pause',
    '&hiText',
    'Soobin searches through the filing cabinets for the give2beomgyu.txt file.',
    '&soobinName',
    '&soobin',
    '"Ah ha! Here it is!"',
    '&bgOffice',
    '&taehyun',
    '"Manager Taehyun (HTTP)! I have the give2beomgyu.txt file!"',
    '&taehyunNameAlt',
    '"Good work, son. Now, I have an even bigger task for you."',
    '&nameBye',
    'Soobin sweats.',
    '&soobinName',
    '"W-what is it?"',
    '&taehyunName',
    '"Son, I need you to encrypt this message. And then squish it."',
    '&byeText',
    '&soobinBye',
    '&taehyunBye',
    '&nameBye',
    '&2layerAnnounce',
    'pause',
    '&hiText',
    '&byeLayer',
    '&taehyun',
    '&soobin',
    '&soobinName',
    '"⁉️"',
    '"What...?"',
    '&taehyunName',
    '"Don\'t worry boy. Here\'s a tutorial."',
    '&encryptGame',
    '"Good work, Soobin! You\'re shaping up to be a top notch employee!"',
    '&soobinName',
    '"Wow... thanks boss!"',
    '&taehyunName',
    '"No problem, kid. But you still got another task."',
    '&removeBg',
    '&taehyunBye',
    '&soobinBye',
    '"The squishing."',
    '&squishGame',
    '&bgOffice',
    '&soobin',
    '&taehyun',
    '"Yay, you did it!"',
    '"But unfortunately, Soobin, I have to go to a VERY important meeting. You\'re gonna need to go to the neighboring department and find Supervisor Yeonjun. He can assist with the rest of your project for the day."',
    '&byeText',
    '&soobinBye',
    '&taehyunBye',
    '&nameBye',
    '&3layerAnnounce',
    'pause',
    '&hiText',
    '&byeLayer',
    '&taehyun',
    '&soobin',
    '&soobinName',
    '"Oh, alright! Well then, I\'ll see you tomorrow, manager Taehyun (Hyun Tae Tae Pop)!"',
    '&taehyunNameAlt',
    '"Bye now, son. And remember, keep your eye on the target!"',
    '&nameBye',
    'Manager Taehyun winks at Soobin. Soobin is suddenly very uncomfortable.',
    '&soobinName',
    '"Um, alright... Bye now..."',
    '&taehyunBye',
    '&nameBye',
    'Soobin walks over to the door that connects the neighboring department to theirs.',
    '&bgClosedDoor',
    '&soobinBye',
    '&soobinName',
    '"Hm... I wonder how I can open this door..."',
    `"Gee, there's gotta be a button SOMEWHERE..."`
        `&doorOpenGame`,
    `&bgOpenDoor`,
    `"Wow! I opened the door! Yay!"`,
    `&secretName`,
    `&yeonjun`,
    `"Hello."`,
    `&soobin`,
    `&soobinName`,
    `"GAH!"`,
    `"Who in the world are you?!"`,
    `&yeonjunName`,
    `"I am the supervisor of the department next door, Yeonjun. I've heard of your task to transport this message to its correct reciever."`,
    `"I am here to assist you, Soobin. Follow me to my office."`,
    `&bgYjOffice`,
    `&nameBye`,
    `&soobinBye`,
    `&yeonjunBye`,
    `Soobin follows supervisor Yeonjun through the door to another office that looks absolutely nothing like his. And is really low resolution. What does this say about the company's values?`,
    `&byeText`,
    '&4layerAnnounce',
    'pause',
    '&hiText',
    '&byeLayer',
    `&yeonjunName`,
    `&soobin`,
    `&yeonjun`,
    `"Listen here, kid. Can I call you kid? Of course I can. In your quest to send this message, you're going to become a bit of a mailman."`,
    `"There's not much I can do for you here, but I can tell you your next course of action."`,
    `"The recipent of this message stays in an office across the city. You're gonna have a couple of choices on how to get there."`,
    `"If you want to get there fast, the UDP train is the fastest in the town. There's a whole lotta people on there too."`,
    `"However, it breaks down pretty easily, so while you'll get there faster, you may encounter some issues on the way there."`,
    `"The second method is the ol' reliable. Walking the TCP sidewalk."`,
    `"Yeah sure, it'll take a while, but theres no risk involved in this fantasy world where walking on the sidewalk is extremely safe."`,
    `&nameBye`,
    `Soobin mulls over this for a second. He still needs to do his SOOBIN best, but he can only do that if he's the most efficent employee alive.`,
    `Who knows if he'll even make it to the recipent's office alive if he takes the UDP train?`,
    `And what if by the time he's done walking the TCP sidewalk, it's too dark out for Soobin to deliver the message?`,
    `Gosh, he just doesn't know.`,
    `What will he pick?`
];